### ISSUE TITLE
Do not package `out` (reduce the package size more than 5000 times).

### ISSUE THREAD

**Issue by ChALkeR** [lazywithclass/egon#4]
_Disclaimer: I am not a user of this package, this was found during mass npm package downloading._

Atm, your npm package `egon@0.4.1` has packaged size **20.88 MiB**, and installed size **231.61 MiB**.

**231.57 MiB** of that is consumed by the file `./out` (looks like some requests log file, something about Android, Motorolla TC55, battery, elemez.apk, etc.).

I suspect that that file was accidently packaged.

You could add it to `.gitignore`.

**Comment by lazywithclass** [comment]
Damn.

Thank you so much for this.
